/**
 * Manually maintained database types for `supabase/migrations/0001_initial_crm_schema.sql`.
 *
 * NOT generated by the Supabase CLI (`supabase gen types typescript`) — CLI
 * type generation is blocked in this environment (native binary execution
 * disallowed by a Windows Application Control policy). Once available, run:
 *
 *   npx supabase gen types typescript --linked > lib/supabase/database.types.ts
 *
 * and this file can be replaced wholesale. Keep this file in sync with the
 * migration by hand until then.
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type ProfileRole = "admin" | "user";

export type WebsiteCheckStatus = "UNKNOWN" | "CHECKED" | "ERROR";

export type LeadStatus =
  | "NEW"
  | "ANALYZING"
  | "QUALIFIED"
  | "DISQUALIFIED"
  | "DEMO_PENDING"
  | "DEMO_CREATED"
  | "OUTREACH_READY"
  | "QUEUED"
  | "CONTACTED"
  | "REPLIED"
  | "INTERESTED"
  | "NOT_INTERESTED"
  | "CONVERTED"
  | "LOST"
  | "DO_NOT_CONTACT";

export type LeadPriority = "LOW" | "MEDIUM" | "HIGH" | "HOT";

export type LeadQualificationStatus =
  | "PENDING"
  | "QUALIFIED"
  | "DISQUALIFIED"
  | "MANUAL_REVIEW";

export type DemoStatus =
  | "DRAFT"
  | "GENERATING"
  | "GENERATED"
  | "DEPLOYMENT_PENDING"
  | "DEPLOYED"
  | "FAILED"
  | "ARCHIVED";

export type DemoDeploymentStatus =
  | "PENDING"
  | "BUILDING"
  | "READY"
  | "FAILED"
  | "CANCELLED";

export type CampaignStatus = "DRAFT" | "ACTIVE" | "PAUSED" | "COMPLETED";

export type OutreachChannel = "email";

export type OutreachMessageStatus =
  | "DRAFT"
  | "PENDING_APPROVAL"
  | "QUEUED"
  | "SENDING"
  | "SENT"
  | "FAILED"
  | "BOUNCED"
  | "REPLIED"
  | "CANCELLED";

export type OutreachEventType =
  | "QUEUED"
  | "SENT"
  | "DELIVERED"
  | "OPENED"
  | "CLICKED"
  | "REPLIED"
  | "BOUNCED"
  | "COMPLAINT"
  | "UNSUBSCRIBED"
  | "FAILED";

export type FollowupStatus =
  | "SCHEDULED"
  | "READY"
  | "SENT"
  | "CANCELLED"
  | "SKIPPED";

export type AutomationRunStatus =
  | "RUNNING"
  | "COMPLETED"
  | "PARTIAL"
  | "FAILED"
  | "CANCELLED";

export type AutomationJobType =
  | "DISCOVER_BUSINESSES"
  | "CHECK_WEBSITE"
  | "ANALYZE_LEAD"
  | "SCORE_LEAD"
  | "GENERATE_DEMO"
  | "DEPLOY_DEMO"
  | "GENERATE_OUTREACH"
  | "PROCESS_OUTREACH"
  | "PROCESS_FOLLOWUP";

export type AutomationJobStatus =
  | "PENDING"
  | "RUNNING"
  | "COMPLETED"
  | "FAILED"
  | "RETRY"
  | "CANCELLED";

export type ApiUsageProvider = "google_places" | "anthropic" | "vercel" | "email";

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          full_name: string | null;
          avatar_url: string | null;
          role: ProfileRole;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          full_name?: string | null;
          avatar_url?: string | null;
          role?: ProfileRole;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["profiles"]["Insert"]>;
        Relationships: [];
      };
      businesses: {
        Row: {
          id: string;
          google_place_id: string | null;
          business_name: string;
          normalized_business_name: string | null;
          category: string | null;
          subcategory: string | null;
          phone: string | null;
          email: string | null;
          website_url: string | null;
          has_website: boolean;
          website_checked_at: string | null;
          website_check_status: WebsiteCheckStatus;
          address: string | null;
          city: string | null;
          state: string | null;
          country: string | null;
          postal_code: string | null;
          latitude: number | null;
          longitude: number | null;
          rating: number | null;
          review_count: number | null;
          google_maps_url: string | null;
          opening_hours: Json | null;
          social_links: Json | null;
          source: string;
          raw_data: Json | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          google_place_id?: string | null;
          business_name: string;
          normalized_business_name?: string | null;
          category?: string | null;
          subcategory?: string | null;
          phone?: string | null;
          email?: string | null;
          website_url?: string | null;
          has_website?: boolean;
          website_checked_at?: string | null;
          website_check_status?: WebsiteCheckStatus;
          address?: string | null;
          city?: string | null;
          state?: string | null;
          country?: string | null;
          postal_code?: string | null;
          latitude?: number | null;
          longitude?: number | null;
          rating?: number | null;
          review_count?: number | null;
          google_maps_url?: string | null;
          opening_hours?: Json | null;
          social_links?: Json | null;
          source?: string;
          raw_data?: Json | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["businesses"]["Insert"]>;
        Relationships: [];
      };
      leads: {
        Row: {
          id: string;
          business_id: string;
          status: LeadStatus;
          priority: LeadPriority;
          lead_score: number;
          qualification_status: LeadQualificationStatus;
          source: string | null;
          notes: string | null;
          assigned_to: string | null;
          first_contacted_at: string | null;
          last_contacted_at: string | null;
          last_replied_at: string | null;
          converted_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          business_id: string;
          status?: LeadStatus;
          priority?: LeadPriority;
          lead_score?: number;
          qualification_status?: LeadQualificationStatus;
          source?: string | null;
          notes?: string | null;
          assigned_to?: string | null;
          first_contacted_at?: string | null;
          last_contacted_at?: string | null;
          last_replied_at?: string | null;
          converted_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["leads"]["Insert"]>;
        Relationships: [];
      };
      lead_scores: {
        Row: {
          id: string;
          lead_id: string;
          score: number;
          website_score: number | null;
          rating_score: number | null;
          review_score: number | null;
          phone_score: number | null;
          email_score: number | null;
          category_score: number | null;
          activity_score: number | null;
          reasoning: string | null;
          scoring_version: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          lead_id: string;
          score?: number;
          website_score?: number | null;
          rating_score?: number | null;
          review_score?: number | null;
          phone_score?: number | null;
          email_score?: number | null;
          category_score?: number | null;
          activity_score?: number | null;
          reasoning?: string | null;
          scoring_version?: string;
          created_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["lead_scores"]["Insert"]>;
        Relationships: [];
      };
      lead_analysis: {
        Row: {
          id: string;
          lead_id: string;
          business_summary: string | null;
          target_customer: string | null;
          services: Json | null;
          recommended_pages: Json | null;
          recommended_features: Json | null;
          design_style: string | null;
          recommended_colors: Json | null;
          recommended_ctas: Json | null;
          pain_points: Json | null;
          personalization_points: Json | null;
          ai_provider: string | null;
          ai_model: string | null;
          prompt_version: string | null;
          raw_response: Json | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          lead_id: string;
          business_summary?: string | null;
          target_customer?: string | null;
          services?: Json | null;
          recommended_pages?: Json | null;
          recommended_features?: Json | null;
          design_style?: string | null;
          recommended_colors?: Json | null;
          recommended_ctas?: Json | null;
          pain_points?: Json | null;
          personalization_points?: Json | null;
          ai_provider?: string | null;
          ai_model?: string | null;
          prompt_version?: string | null;
          raw_response?: Json | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["lead_analysis"]["Insert"]>;
        Relationships: [];
      };
      demo_templates: {
        Row: {
          id: string;
          name: string;
          slug: string;
          category: string;
          description: string | null;
          preview_image_url: string | null;
          configuration: Json | null;
          active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          slug: string;
          category: string;
          description?: string | null;
          preview_image_url?: string | null;
          configuration?: Json | null;
          active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["demo_templates"]["Insert"]>;
        Relationships: [];
      };
      demos: {
        Row: {
          id: string;
          lead_id: string;
          template_id: string | null;
          name: string;
          slug: string;
          status: DemoStatus;
          repository_url: string | null;
          deployment_url: string | null;
          preview_url: string | null;
          generated_content: Json | null;
          generation_error: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          lead_id: string;
          template_id?: string | null;
          name: string;
          slug: string;
          status?: DemoStatus;
          repository_url?: string | null;
          deployment_url?: string | null;
          preview_url?: string | null;
          generated_content?: Json | null;
          generation_error?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["demos"]["Insert"]>;
        Relationships: [];
      };
      demo_deployments: {
        Row: {
          id: string;
          demo_id: string;
          provider: string;
          deployment_id: string | null;
          repository_url: string | null;
          deployment_url: string | null;
          status: DemoDeploymentStatus;
          error_message: string | null;
          attempt_count: number;
          started_at: string | null;
          completed_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          demo_id: string;
          provider?: string;
          deployment_id?: string | null;
          repository_url?: string | null;
          deployment_url?: string | null;
          status?: DemoDeploymentStatus;
          error_message?: string | null;
          attempt_count?: number;
          started_at?: string | null;
          completed_at?: string | null;
          created_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["demo_deployments"]["Insert"]>;
        Relationships: [];
      };
      campaigns: {
        Row: {
          id: string;
          name: string;
          description: string | null;
          status: CampaignStatus;
          locations: Json | null;
          categories: Json | null;
          daily_discovery_limit: number;
          daily_demo_limit: number;
          daily_outreach_limit: number;
          start_date: string | null;
          end_date: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          description?: string | null;
          status?: CampaignStatus;
          locations?: Json | null;
          categories?: Json | null;
          daily_discovery_limit?: number;
          daily_demo_limit?: number;
          daily_outreach_limit?: number;
          start_date?: string | null;
          end_date?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["campaigns"]["Insert"]>;
        Relationships: [];
      };
      outreach_messages: {
        Row: {
          id: string;
          lead_id: string;
          campaign_id: string | null;
          channel: OutreachChannel;
          recipient_email: string | null;
          subject: string | null;
          message_body: string | null;
          status: OutreachMessageStatus;
          scheduled_at: string | null;
          sent_at: string | null;
          provider_message_id: string | null;
          attempt_count: number;
          error_message: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          lead_id: string;
          campaign_id?: string | null;
          channel?: OutreachChannel;
          recipient_email?: string | null;
          subject?: string | null;
          message_body?: string | null;
          status?: OutreachMessageStatus;
          scheduled_at?: string | null;
          sent_at?: string | null;
          provider_message_id?: string | null;
          attempt_count?: number;
          error_message?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["outreach_messages"]["Insert"]>;
        Relationships: [];
      };
      outreach_events: {
        Row: {
          id: string;
          message_id: string;
          event_type: OutreachEventType;
          provider_event_id: string | null;
          metadata: Json | null;
          occurred_at: string;
        };
        Insert: {
          id?: string;
          message_id: string;
          event_type: OutreachEventType;
          provider_event_id?: string | null;
          metadata?: Json | null;
          occurred_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["outreach_events"]["Insert"]>;
        Relationships: [];
      };
      followups: {
        Row: {
          id: string;
          lead_id: string;
          parent_message_id: string | null;
          sequence_number: number;
          status: FollowupStatus;
          scheduled_at: string | null;
          sent_at: string | null;
          cancelled_at: string | null;
          reason: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          lead_id: string;
          parent_message_id?: string | null;
          sequence_number: number;
          status?: FollowupStatus;
          scheduled_at?: string | null;
          sent_at?: string | null;
          cancelled_at?: string | null;
          reason?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["followups"]["Insert"]>;
        Relationships: [];
      };
      suppression_list: {
        Row: {
          id: string;
          email: string | null;
          phone: string | null;
          business_id: string | null;
          reason: string | null;
          source: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          email?: string | null;
          phone?: string | null;
          business_id?: string | null;
          reason?: string | null;
          source?: string | null;
          created_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["suppression_list"]["Insert"]>;
        Relationships: [];
      };
      automation_settings: {
        Row: {
          id: string;
          enabled: boolean;
          discovery_enabled: boolean;
          ai_analysis_enabled: boolean;
          demo_generation_enabled: boolean;
          auto_deployment_enabled: boolean;
          auto_outreach_enabled: boolean;
          followups_enabled: boolean;
          require_outreach_approval: boolean;
          daily_discovery_limit: number;
          daily_ai_limit: number;
          daily_demo_limit: number;
          daily_deployment_limit: number;
          daily_outreach_limit: number;
          hourly_outreach_limit: number;
          followup_1_delay_days: number;
          followup_2_delay_days: number;
          timezone: string;
          demo_mode: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: Partial<Database["public"]["Tables"]["automation_settings"]["Row"]>;
        Update: Partial<Database["public"]["Tables"]["automation_settings"]["Row"]>;
        Relationships: [];
      };
      automation_runs: {
        Row: {
          id: string;
          status: AutomationRunStatus;
          started_at: string;
          completed_at: string | null;
          businesses_found: number;
          duplicates_removed: number;
          no_website_found: number;
          qualified_leads: number;
          demos_created: number;
          deployments_successful: number;
          messages_generated: number;
          messages_queued: number;
          messages_sent: number;
          followups_created: number;
          error_count: number;
          metadata: Json | null;
          error_message: string | null;
        };
        Insert: {
          id?: string;
          status?: AutomationRunStatus;
          started_at?: string;
          completed_at?: string | null;
          businesses_found?: number;
          duplicates_removed?: number;
          no_website_found?: number;
          qualified_leads?: number;
          demos_created?: number;
          deployments_successful?: number;
          messages_generated?: number;
          messages_queued?: number;
          messages_sent?: number;
          followups_created?: number;
          error_count?: number;
          metadata?: Json | null;
          error_message?: string | null;
        };
        Update: Partial<Database["public"]["Tables"]["automation_runs"]["Insert"]>;
        Relationships: [];
      };
      automation_jobs: {
        Row: {
          id: string;
          job_type: AutomationJobType;
          status: AutomationJobStatus;
          lead_id: string | null;
          run_id: string | null;
          attempt_count: number;
          max_attempts: number;
          scheduled_at: string;
          started_at: string | null;
          completed_at: string | null;
          error_message: string | null;
          payload: Json | null;
          result: Json | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          job_type: AutomationJobType;
          status?: AutomationJobStatus;
          lead_id?: string | null;
          run_id?: string | null;
          attempt_count?: number;
          max_attempts?: number;
          scheduled_at?: string;
          started_at?: string | null;
          completed_at?: string | null;
          error_message?: string | null;
          payload?: Json | null;
          result?: Json | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["automation_jobs"]["Insert"]>;
        Relationships: [];
      };
      api_usage: {
        Row: {
          id: string;
          provider: ApiUsageProvider;
          operation: string;
          quantity: number;
          estimated_cost: number | null;
          metadata: Json | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          provider: ApiUsageProvider;
          operation: string;
          quantity?: number;
          estimated_cost?: number | null;
          metadata?: Json | null;
          created_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["api_usage"]["Insert"]>;
        Relationships: [];
      };
      error_logs: {
        Row: {
          id: string;
          service: string | null;
          error_code: string | null;
          message: string | null;
          lead_id: string | null;
          run_id: string | null;
          job_id: string | null;
          metadata: Json | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          service?: string | null;
          error_code?: string | null;
          message?: string | null;
          lead_id?: string | null;
          run_id?: string | null;
          job_id?: string | null;
          metadata?: Json | null;
          created_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["error_logs"]["Insert"]>;
        Relationships: [];
      };
      audit_logs: {
        Row: {
          id: string;
          user_id: string | null;
          action: string;
          entity_type: string | null;
          entity_id: string | null;
          metadata: Json | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id?: string | null;
          action: string;
          entity_type?: string | null;
          entity_id?: string | null;
          metadata?: Json | null;
          created_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["audit_logs"]["Insert"]>;
        Relationships: [];
      };
    };
    Views: Record<string, never>;
    Functions: {
      is_admin: {
        Args: Record<string, never>;
        Returns: boolean;
      };
    };
    Enums: Record<string, never>;
  };
}
